# Generated by Django 3.2.19 on 2023-06-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitipedia_app', '0002_fruitmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruitmodel',
            options={'ordering': ('pk',)},
        ),
    ]
